# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_generated/entry_points.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_entryPointsView(object):
    def setupUi(self, entryPointsView):
        entryPointsView.setObjectName("entryPointsView")
        entryPointsView.setWindowModality(QtCore.Qt.ApplicationModal)
        entryPointsView.resize(763, 385)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        entryPointsView.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/b_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        entryPointsView.setWindowIcon(icon)
        entryPointsView.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(entryPointsView)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treePoints = QtWidgets.QTreeView(entryPointsView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treePoints.sizePolicy().hasHeightForWidth())
        self.treePoints.setSizePolicy(sizePolicy)
        self.treePoints.setMinimumSize(QtCore.QSize(120, 0))
        self.treePoints.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treePoints.setObjectName("treePoints")
        self.horizontalLayout.addWidget(self.treePoints)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.point_name = QtWidgets.QLabel(entryPointsView)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.point_name.setFont(font)
        self.point_name.setText("")
        self.point_name.setObjectName("point_name")
        self.verticalLayout.addWidget(self.point_name)
        self.pointText = QtWidgets.QTextBrowser(entryPointsView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pointText.sizePolicy().hasHeightForWidth())
        self.pointText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.pointText.setFont(font)
        self.pointText.setObjectName("pointText")
        self.verticalLayout.addWidget(self.pointText)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(entryPointsView)
        QtCore.QMetaObject.connectSlotsByName(entryPointsView)

    def retranslateUi(self, entryPointsView):
        _translate = QtCore.QCoreApplication.translate
        entryPointsView.setWindowTitle(_translate("entryPointsView", "Bionic - entry points"))
from application.ui.qt_generated import res_rc
