# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_generated/itembook_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_itemWidget(object):
    def setupUi(self, itemWidget):
        itemWidget.setObjectName("itemWidget")
        itemWidget.resize(573, 103)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        itemWidget.setFont(font)
        itemWidget.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(itemWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cover_label = QtWidgets.QLabel(itemWidget)
        self.cover_label.setMinimumSize(QtCore.QSize(110, 85))
        self.cover_label.setMaximumSize(QtCore.QSize(110, 85))
        self.cover_label.setText("")
        self.cover_label.setScaledContents(True)
        self.cover_label.setObjectName("cover_label")
        self.horizontalLayout.addWidget(self.cover_label)
        self.name_label = QtWidgets.QLabel(itemWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label.sizePolicy().hasHeightForWidth())
        self.name_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.name_label.setFont(font)
        self.name_label.setStyleSheet("")
        self.name_label.setScaledContents(False)
        self.name_label.setWordWrap(True)
        self.name_label.setObjectName("name_label")
        self.horizontalLayout.addWidget(self.name_label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.date_label = QtWidgets.QLabel(itemWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_label.sizePolicy().hasHeightForWidth())
        self.date_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.date_label.setFont(font)
        self.date_label.setStyleSheet("")
        self.date_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.date_label.setObjectName("date_label")
        self.verticalLayout.addWidget(self.date_label)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(itemWidget)
        QtCore.QMetaObject.connectSlotsByName(itemWidget)

    def retranslateUi(self, itemWidget):
        _translate = QtCore.QCoreApplication.translate
        itemWidget.setWindowTitle(_translate("itemWidget", "Form"))
        self.name_label.setText(_translate("itemWidget", "Name"))
        self.date_label.setText(_translate("itemWidget", "date"))
